<?php
/**
 * Mock provider.
 *
 * Returns a deterministic, schema-valid SaaS landing page so the
 * end-to-end pipeline (REST → validator → composer → renderer) can be
 * exercised without any API keys. This is the default after install.
 *
 * @package OxaAi
 */

declare(strict_types=1);

namespace OxaAi\Providers;

if (!defined('ABSPATH')) {
    exit;
}

final class MockProvider implements ProviderInterface
{
    public function slug(): string         { return 'mock'; }
    public function label(): string        { return 'Mock (offline)'; }
    public function isConfigured(): bool   { return true; }
    public function defaultModel(): string { return 'mock-v1'; }

    public function complete(array $messages, array $options = []): string
    {
        $title = $this->extractTitleFromPrompt($this->unwrapUserPrompt((string) ($messages['user'] ?? '')));

        $page = [
            'page_title' => $title,
            'layout'     => [
                [
                    'component' => 'hero',
                    'props'     => [
                        'eyebrow'            => 'AI-Generated',
                        'title'              => $title,
                        'subtitle'           => 'This page was generated by the Oxa mock provider. Switch to OpenAI or Claude in settings to use a real model.',
                        'primary_cta_text'   => 'Get started',
                        'primary_cta_link'   => '#get-started',
                        'secondary_cta_text' => 'Read docs',
                        'secondary_cta_link' => '#docs',
                        'align'              => 'center',
                    ],
                ],
                [
                    'component' => 'features',
                    'props'     => [
                        'heading' => 'Why teams choose us',
                        'intro'   => 'Three reasons to take a closer look.',
                        'columns' => '3',
                        'items'   => [
                            ['icon' => '⚡', 'title' => 'Fast',     'description' => 'Ship pages in seconds, not days.'],
                            ['icon' => '🧩', 'title' => 'Composable','description' => 'Every section is a typed, validated component.'],
                            ['icon' => '🛡', 'title' => 'Safe',     'description' => 'AI never edits raw HTML — only validated JSON.'],
                        ],
                    ],
                ],
                [
                    'component' => 'cta',
                    'props'     => [
                        'title'    => 'Ready to build with AI?',
                        'subtitle' => 'Connect a real provider in WP Admin → Oxa AI → Settings.',
                        'cta_text' => 'Open settings',
                        'cta_link' => '#',
                        'variant'  => 'solid',
                    ],
                ],
            ],
        ];

        return wp_json_encode($page, JSON_UNESCAPED_SLASHES);
    }

    /**
     * Strip the deterministic wrapper that PromptBuilder applies so the
     * mock provider sees only the user's original text.
     */
    private function unwrapUserPrompt(string $wrapped): string
    {
        if (preg_match("/^User request:\s*\n(.*?)\n\nReturn the page JSON now\.\s*$/s", $wrapped, $m) === 1) {
            return $m[1];
        }
        return $wrapped;
    }

    private function extractTitleFromPrompt(string $prompt): string
    {
        $prompt = trim($prompt);
        if ($prompt === '') {
            return 'New Page';
        }
        $first = preg_split('/[\.\?!\n]/', $prompt, 2)[0] ?? '';
        $first = trim($first);
        if ($first === '') {
            return 'New Page';
        }
        return mb_strimwidth($first, 0, 80, '…');
    }
}
